export default {
  avr: {
    label: "AVR (e.g. UNO, Yùn, Mega)",
    serial: true,
    progmem: true,
    ramWarning: 1024,
    ramError: 8192,
    nestingLimit: 10,
    slotSize: 8,
    poolCapacity: 16,
    useLongLong: { default: false, slotSize: 12 },
  },
  ameba: {
    label: "Ameba D",
    serial: true,
    heapThreshold: 2048,
    ramWarning: 1024 * 1024,
    ramError: 4 * 1024 * 1024,
    nestingLimit: 10,
    slotSize: 16,
    poolCapacity: 64,
    useLongLong: { default: true, slotSize: 16 },
    useDouble: { default: true, slotSize: 16 },
  },
  esp32: {
    label: "ESP32",
    serial: true,
    heapThreshold: 2048,
    ramWarning: 100 * 1024,
    ramError: 500 * 1024,
    nestingLimit: 10,
    slotSize: 16,
    poolCapacity: 64,
    useLongLong: { default: true, slotSize: 16 },
    useDouble: { default: true, slotSize: 16 },
  },
  esp8266: {
    label: "ESP8266",
    serial: true,
    progmem: true,
    heapThreshold: 1024,
    ramWarning: 30 * 1024,
    ramError: 80 * 1024,
    nestingLimit: 10,
    slotSize: 16,
    poolCapacity: 64,
    useLongLong: { default: true, slotSize: 16 },
    useDouble: { default: true, slotSize: 16 },
  },
  nios2: {
    label: "Nios II",
    heapThreshold: 2048,
    ramWarning: 1024 * 1024,
    ramError: 16 * 1024 * 1024,
    nestingLimit: 10,
    slotSize: 16,
    poolCapacity: 64,
    useLongLong: { default: true, slotSize: 16 },
    useDouble: { default: true, slotSize: 16 },
  },
  samd21: {
    label: "SAMD21",
    serial: true,
    heapThreshold: 1024,
    ramWarning: 10 * 1024,
    ramError: 30 * 1024,
    nestingLimit: 10,
    slotSize: 16,
    poolCapacity: 64,
    useLongLong: { default: true, slotSize: 16 },
    useDouble: { default: true, slotSize: 16 },
  },
  stm32: {
    label: "STM32",
    serial: true,
    heapThreshold: 1024,
    ramWarning: 10 * 1024,
    ramError: 100 * 1024,
    nestingLimit: 10,
    slotSize: 16,
    poolCapacity: 64,
    useLongLong: { default: true, slotSize: 16 },
    useDouble: { default: true, slotSize: 16 },
  },
  x86: {
    label: "x86",
    serial: false,
    heapThreshold: 4096,
    nestingLimit: 10,
    slotSize: 16,
    poolCapacity: 64,
    useDouble: { default: true, slotSize: 16 },
    useLongLong: { default: true, slotSize: 16 },
  },
  x64: {
    label: "x64",
    serial: false,
    heapThreshold: 4096,
    nestingLimit: 10,
    slotSize: 32,
    poolCapacity: 128,
    useDouble: { default: true, slotSize: 32 },
    useLongLong: { default: true, slotSize: 32 },
  },
};
