name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
      - run: npm run test
      - run: npm run build -- --base=/v5/
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/5.x'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: v5
